import type { Allocation, Recipient, Receipt, SettlementState } from "./types";
const positiveInteger=(n:number)=>Number.isInteger(n)&&n>0;
export const allocationQuantity=(itemId:string, allocations:Allocation[])=>allocations.filter(a=>a.receiptItemId===itemId).reduce((s,a)=>s+a.quantity,0);
export function assertAllocation(receipt:Receipt, allocations:Allocation[], itemId:string, quantity:number, replacingId?:string) { if(!positiveInteger(quantity)) throw new Error("배분 수량은 0이 아닌 양의 정수여야 합니다."); const item=receipt.items.find(i=>i.id===itemId); if(!item) throw new Error("영수증 품목을 찾을 수 없습니다."); const used=allocationQuantity(itemId,allocations.filter(a=>a.id!==replacingId)); if(used+quantity>item.quantityValue) throw new Error(`구매 수량(${item.quantityValue})을 초과할 수 없습니다.`); }
export function assertRecipientDeletable(id:string, allocations:Allocation[]) { if(allocations.some(a=>a.recipientId===id)) throw new Error("연결된 배분이 있어 수령자를 삭제할 수 없습니다."); }
export function recipientTotal(receipt:Receipt, recipientId:string, allocations:Allocation[]) { return allocations.filter(a=>a.recipientId===recipientId).reduce((s,a)=>s+(receipt.items.find(i=>i.id===a.receiptItemId)?.unitPriceKrw ?? 0)*a.quantity,0); }
export function overview(receipt:Receipt,state:SettlementState) { const allocated=state.allocations.reduce((s,a)=>s+(receipt.items.find(i=>i.id===a.receiptItemId)?.unitPriceKrw ?? 0)*a.quantity,0); const allocatedQuantity=state.allocations.reduce((s,a)=>s+a.quantity,0); const paid=state.settlementStatuses.filter(s=>s.paymentStatus==="입금 완료").reduce((sum,s)=>sum+recipientTotal(receipt,s.recipientId,state.allocations),0); return { allocatedKrw:allocated, unallocatedKrw:receipt.totalPriceKrw-allocated, paidKrw:paid, unpaidKrw:allocated-paid, allocatedQuantity, remainingQuantity:receipt.items.reduce((s,i)=>s+i.quantityValue,0)-allocatedQuantity }; }
export function settlementMessage(receipt:Receipt, recipient:Recipient, allocations:Allocation[]) { const lines=allocations.filter(a=>a.recipientId===recipient.id).map(a=>{const item=receipt.items.find(i=>i.id===a.receiptItemId)!; return `- ${item.productName} ${a.quantity}개 · ${formatKrw(item.unitPriceKrw*a.quantity)}`}); return `[${receipt.storeLabel} 정산]\n${recipient.name}님\n${lines.join("\n")}\n합계 ${formatKrw(recipientTotal(receipt,recipient.id,allocations))}`; }
export const formatKrw=(value:number)=>`${new Intl.NumberFormat("ko-KR").format(value)}원`;
