export type Json = string | number | boolean | null | { [key:string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { id:string; display_name:string|null; created_at:string }; Insert: { id:string; display_name?:string|null }; Update: { display_name?:string|null } };
      stores: { Row: { id:string; user_id:string; name:string; created_at:string }; Insert: { id?:string; user_id:string; name:string }; Update: { name?:string } };
      catalog_categories: { Row: { id:string; purchase_type:string; parent_id:string|null; slug:string; display_name:string; depth:number }; Insert: { id?:string; purchase_type:string; parent_id?:string|null; slug:string; display_name:string; depth?:number }; Update: { parent_id?:string|null; display_name?:string; depth?:number } };
      brands: { Row: { id:string; canonical_name:string; normalized_name:string; logo_url:string|null; official_site_url:string|null; status:string; created_by:string|null; created_at:string; updated_at:string }; Insert: { id?:string; canonical_name:string; logo_url?:string|null; official_site_url?:string|null; status?:string; created_by?:string|null }; Update: { canonical_name?:string; logo_url?:string|null; official_site_url?:string|null; status?:string } };
      brand_aliases: { Row: { id:string; brand_id:string; alias_name:string; normalized_alias:string; locale:string|null; created_by:string|null; created_at:string }; Insert: { id?:string; brand_id:string; alias_name:string; locale?:string|null; created_by?:string|null }; Update: { brand_id?:string; alias_name?:string; locale?:string|null } };
      standard_products: { Row: { id:string; purchase_type:string; canonical_name:string; brand_id:string|null; brand:string|null; product_reference_url:string|null; category_id:string|null; status:string; created_by:string|null; created_at:string; updated_at:string }; Insert: { id?:string; purchase_type:string; canonical_name:string; brand_id?:string|null; product_reference_url?:string|null; category_id?:string|null; status?:string; created_by?:string|null }; Update: { canonical_name?:string; brand_id?:string|null; product_reference_url?:string|null; category_id?:string|null; status?:string } };
      standard_product_brand_evidence: { Row: { id:string; standard_product_id:string; catalog_product_id:string|null; brand_id:string; observed_name:string; normalized_observed_name:string; source_type:"receipt"|"official_store"|"manual"|"legacy_import"; source_label:string|null; source_product_code:string|null; source_url:string|null; observed_at:string; created_by:string|null; created_at:string }; Insert: { id?:string; standard_product_id:string; catalog_product_id?:string|null; brand_id:string; observed_name:string; source_type:"receipt"|"official_store"|"manual"|"legacy_import"; source_label?:string|null; source_product_code?:string|null; source_url?:string|null; observed_at?:string; created_by?:string|null }; Update: { brand_id?:string; observed_name?:string; source_type?:"receipt"|"official_store"|"manual"|"legacy_import"; source_label?:string|null; source_product_code?:string|null; source_url?:string|null; observed_at?:string } };
      standard_product_link_executions: { Row: { id:string; idempotency_key:string; case_id:string; input_fingerprint:string; target_fingerprint:string; status:"in_progress"|"applied"; standard_product_id:string|null; catalog_product_id:string|null; result:Json|null; request_payload:Json|null; proposal_input:Json|null; proposal_target:Json|null; created_by:string|null; created_at:string; applied_at:string|null }; Insert: { id?:string; idempotency_key:string; case_id:string; input_fingerprint:string; target_fingerprint:string; status?:"in_progress"|"applied"; standard_product_id?:string|null; catalog_product_id?:string|null; result?:Json|null; request_payload?:Json|null; proposal_input?:Json|null; proposal_target?:Json|null; created_by?:string|null; applied_at?:string|null }; Update: { status?:"in_progress"|"applied"; standard_product_id?:string|null; catalog_product_id?:string|null; result?:Json|null; request_payload?:Json|null; proposal_input?:Json|null; proposal_target?:Json|null; applied_at?:string|null } };
      standard_product_link_approvals: { Row: { id:string; case_id:string; input_fingerprint:string; target_fingerprint:string; approval_statement:string; user_approval_text:string|null; approval_policy:string; proposal_input:Json; proposal_target:Json; approved_by:string; approved_at:string; consumed_execution_id:string|null; consumed_at:string|null }; Insert: { id?:string; case_id:string; input_fingerprint:string; target_fingerprint:string; approval_statement:string; user_approval_text?:string|null; approval_policy:string; proposal_input:Json; proposal_target:Json; approved_by:string; approved_at?:string; consumed_execution_id?:string|null; consumed_at?:string|null }; Update: { user_approval_text?:string|null; consumed_execution_id?:string|null; consumed_at?:string|null } };
      standard_product_official_image_approvals: { Row: { id:string; idempotency_key:string; case_id:string; input_fingerprint:string; target_fingerprint:string; approval_statement:string; proposal:Json; standard_product_id:string; catalog_product_id:string; official_link_id:string; image_url:string; content_hash:string; media_type:"image/jpeg"|"image/png"|"image/webp"; byte_length:number; applied_action:"created"|"reused_exact"; result:Json; approved_by:string; approved_at:string }; Insert: { id?:string; idempotency_key:string; case_id:string; input_fingerprint:string; target_fingerprint:string; approval_statement:string; proposal:Json; standard_product_id:string; catalog_product_id:string; official_link_id:string; image_url:string; content_hash:string; media_type:"image/jpeg"|"image/png"|"image/webp"; byte_length:number; applied_action:"created"|"reused_exact"; result:Json; approved_by:string; approved_at?:string }; Update: Record<string, never> };
      standard_catalog_admin_actions: { Row: { id:string; action:string; target_id:string; payload:Json; confirmation:string; created_by:string; created_at:string }; Insert: { id?:string; action:string; target_id:string; payload:Json; confirmation:string; created_by:string; created_at?:string }; Update: Record<string, never> };
      standard_product_official_links: { Row: { id:string; channel_id:string; source_product_code_namespace:string; source_product_code:string; catalog_product_id:string; created_by:string|null; created_at:string }; Insert: { id?:string; channel_id:string; source_product_code_namespace:string; source_product_code:string; catalog_product_id:string; created_by?:string|null }; Update: { catalog_product_id?:string } };
      standard_product_official_link_evidence: { Row: { id:string; official_link_id:string; snapshot_id:string; snapshot_hash:string; source_name_raw:string; specification_text_raw:string; source_refs:Json; product_reference_url:string; link_execution_id:string; created_by:string|null; created_at:string }; Insert: { id?:string; official_link_id:string; snapshot_id:string; snapshot_hash:string; source_name_raw:string; specification_text_raw:string; source_refs:Json; product_reference_url:string; link_execution_id:string; created_by?:string|null }; Update: { snapshot_id?:string; snapshot_hash?:string; source_name_raw?:string; specification_text_raw?:string; source_refs?:Json; product_reference_url?:string } };
      standard_product_images: { Row: { standard_product_id:string; source_type:"upload"|"external_url"; image_url:string; storage_path:string|null; mime_type:string|null; file_size_bytes:number|null; width:number|null; height:number|null; created_by:string|null; created_at:string; updated_at:string }; Insert: { standard_product_id:string; source_type:"upload"|"external_url"; image_url:string; storage_path?:string|null; mime_type?:string|null; file_size_bytes?:number|null; width?:number|null; height?:number|null; created_by?:string|null; updated_at?:string }; Update: { source_type?:"upload"|"external_url"; image_url?:string; storage_path?:string|null; mime_type?:string|null; file_size_bytes?:number|null; width?:number|null; height?:number|null; created_by?:string|null; updated_at?:string } };
      catalog_products: { Row: { id:string; standard_product_id:string; purchase_type:string; canonical_name:string; brand:string|null; specification:string|null; specification_status:"verified"|"placeholder"; content_amount:number|null; content_unit:string|null; package_count:number; reference_unit:number; listing_reference_url:string|null; category_id:string|null; attributes:Json; status:string; created_by:string|null; created_at:string; updated_at:string }; Insert: { id?:string; standard_product_id:string; purchase_type:string; canonical_name:string; specification?:string|null; specification_status?:"verified"|"placeholder"; content_amount?:number|null; content_unit?:string|null; package_count?:number; reference_unit?:number; listing_reference_url?:string|null; category_id?:string|null; attributes?:Json; status?:string; created_by?:string|null }; Update: { standard_product_id?:string; canonical_name?:string; specification?:string|null; specification_status?:"verified"|"placeholder"; content_amount?:number|null; content_unit?:string|null; package_count?:number; reference_unit?:number; listing_reference_url?:string|null; category_id?:string|null; attributes?:Json; status?:string } };
      standard_product_coupang_prices: { Row: { id:string; standard_product_id:string; catalog_product_id:string|null; link_execution_id:string|null; product_url:string; listed_price_krw:number; quantity:number; content_amount:number|null; content_unit:string|null; max_bundle_quantity:number|null; max_bundle_listed_price_krw:number|null; observed_at:string; created_by:string|null; created_at:string }; Insert: { id?:string; standard_product_id:string; catalog_product_id?:string|null; link_execution_id?:string|null; product_url:string; listed_price_krw:number; quantity?:number; content_amount?:number|null; content_unit?:string|null; max_bundle_quantity?:number|null; max_bundle_listed_price_krw?:number|null; observed_at?:string; created_by?:string|null }; Update: { catalog_product_id?:string|null; link_execution_id?:string|null; product_url?:string; listed_price_krw?:number; quantity?:number; content_amount?:number|null; content_unit?:string|null; max_bundle_quantity?:number|null; max_bundle_listed_price_krw?:number|null; observed_at?:string; created_by?:string|null } };
      market_price_observations: { Row: { id:string; catalog_product_id:string; seller_name:string; product_url:string; listed_price_krw:number; shipping_fee_krw:number; minimum_order_quantity:number; observed_at:string; verification_status:string; verified_by:string|null; verified_at:string|null; created_at:string }; Insert: { id?:string; catalog_product_id:string; seller_name:string; product_url:string; listed_price_krw:number; shipping_fee_krw?:number; minimum_order_quantity?:number; observed_at:string; verification_status?:string; verified_by?:string|null; verified_at?:string|null }; Update: { seller_name?:string; product_url?:string; listed_price_krw?:number; shipping_fee_krw?:number; minimum_order_quantity?:number; observed_at?:string; verification_status?:string; verified_by?:string|null; verified_at?:string|null } };
      source_product_mappings: { Row: { id:string; source_label:string; source_product_code:string; catalog_product_id:string; matching_method:string; confidence:number; review_status:string; created_by:string|null; reviewed_by:string|null; reviewed_at:string|null; created_at:string; updated_at:string }; Insert: { id?:string; source_label:string; source_product_code:string; catalog_product_id:string; matching_method?:string; confidence?:number; review_status?:string; created_by?:string|null; reviewed_by?:string|null; reviewed_at?:string|null }; Update: { source_label?:string; source_product_code?:string; catalog_product_id?:string; matching_method?:string; confidence?:number; review_status?:string; reviewed_by?:string|null; reviewed_at?:string|null } };
      products: { Row: { id:string; user_id:string; name:string; purchase_type:string; category_id:string|null; category_tags:string[]; created_at:string }; Insert: { id?:string; user_id:string; name:string; purchase_type?:string; category_id?:string|null; category_tags?:string[] }; Update: { name?:string; purchase_type?:string; category_id?:string|null; category_tags?:string[] } };
      store_products: { Row: { id:string; user_id:string; store_id:string; product_id:string; store_product_code:string }; Insert: { id?:string; user_id:string; store_id:string; product_id:string; store_product_code:string }; Update: { store_product_code?:string } };
      receipts: { Row: { id:string; user_id:string; store_id:string; purchased_at:string; transaction_number:string; total_price_krw:number }; Insert: { id?:string; user_id:string; store_id:string; purchased_at:string; transaction_number:string; total_price_krw:number }; Update: { purchased_at?:string; transaction_number?:string; total_price_krw?:number } };
      receipt_items: { Row: { id:string; user_id:string; receipt_id:string; store_product_id:string; unit_price_krw:number; purchased_quantity:number; total_price_krw:number; purchase_numbers:number[] }; Insert: { id?:string; user_id:string; receipt_id:string; store_product_id:string; unit_price_krw:number; purchased_quantity:number; total_price_krw:number; purchase_numbers:number[] }; Update: { unit_price_krw?:number; purchased_quantity?:number; total_price_krw?:number; purchase_numbers?:number[] } };
      price_observations: { Row: { id:string; user_id:string; store_product_id:string; receipt_item_id:string; catalog_product_id:string|null; observed_at:string; unit_price_krw:number; measurement_unit:string; location_label:string|null; attributes:Json }; Insert: { id?:string; user_id:string; store_product_id:string; receipt_item_id:string; catalog_product_id?:string|null; observed_at:string; unit_price_krw:number; measurement_unit?:string; location_label?:string|null; attributes?:Json }; Update: { catalog_product_id?:string|null; observed_at?:string; unit_price_krw?:number; measurement_unit?:string; location_label?:string|null; attributes?:Json } };
      recipients: { Row: { id:string; user_id:string; name:string; created_at:string }; Insert: { id?:string; user_id:string; name:string }; Update: { name?:string } };
      allocations: { Row: { id:string; user_id:string; receipt_item_id:string; recipient_id:string; quantity:number; memo:string }; Insert: { id?:string; user_id:string; receipt_item_id:string; recipient_id:string; quantity:number; memo?:string }; Update: { quantity?:number; memo?:string } };
      settlement_statuses: { Row: { recipient_id:string; user_id:string; delivery_status:string; payment_status:string; paid_at:string|null }; Insert: { recipient_id:string; user_id:string; delivery_status:string; payment_status:string; paid_at?:string|null }; Update: { delivery_status?:string; payment_status?:string; paid_at?:string|null } };
    };
    Views: Record<string, never>;
    Functions: {
      approve_standard_product_official_image_v1: {
        Args: {
          p_idempotency_key:string;
          p_proposal_canonical_json:string;
          p_approval_statement:string;
          p_standard_product_id:string;
          p_catalog_product_id:string;
        };
        Returns: {
          approval_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
          applied_action:"created"|"reused_exact";
        }[];
      };
      admin_manage_standard_catalog: {
        Args: {
          p_action:string;
          p_target_id:string;
          p_payload:Json;
          p_confirmation:string;
        };
        Returns: string;
      };
      approve_and_register_standard_product_link_only_v1: {
        Args: {
          p_idempotency_key:string;
          p_case_id:string;
          p_input_fingerprint:string;
          p_target_fingerprint:string;
          p_input_canonical_json:string;
          p_target_canonical_json:string;
          p_approval_statement:string;
          p_receipt_id:string;
          p_receipt_item_id:string;
          p_receipt_observed_at:string;
          p_standard_product_id:string|null;
          p_catalog_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_receipt_product_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_specification:string;
          p_apparel_size:Json|null;
        };
        Returns: {
          execution_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
        }[];
      };
      approve_and_register_standard_product_link_strict_v4: {
        Args: {
          p_idempotency_key:string;
          p_case_id:string;
          p_input_fingerprint:string;
          p_target_fingerprint:string;
          p_input_canonical_json:string;
          p_target_canonical_json:string;
          p_approval_statement:string;
          p_receipt_id:string;
          p_receipt_item_id:string;
          p_receipt_observed_at:string;
          p_standard_product_id:string|null;
          p_catalog_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_receipt_product_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          execution_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
        }[];
      };
      approve_and_register_standard_product_link_strict_v5: {
        Args: {
          p_idempotency_key:string;
          p_case_id:string;
          p_input_fingerprint:string;
          p_target_fingerprint:string;
          p_input_canonical_json:string;
          p_target_canonical_json:string;
          p_approval_statement:string;
          p_receipt_id:string;
          p_receipt_item_id:string;
          p_receipt_observed_at:string;
          p_standard_product_id:string|null;
          p_catalog_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_receipt_product_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          execution_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
        }[];
      };
      approve_and_register_standard_product_link_strict_v6: {
        Args: {
          p_idempotency_key:string;
          p_case_id:string;
          p_input_fingerprint:string;
          p_target_fingerprint:string;
          p_input_canonical_json:string;
          p_target_canonical_json:string;
          p_approval_statement:string;
          p_receipt_id:string;
          p_receipt_item_id:string;
          p_receipt_observed_at:string;
          p_standard_product_id:string|null;
          p_catalog_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_receipt_product_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          execution_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
        }[];
      };
      register_standard_product_with_coupang_price: {
        Args: {
          p_standard_product_id:string|null;
          p_standard_name:string;
          p_product_reference_url:string;
          p_listing_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          standard_product_id:string;
          catalog_product_id:string;
        }[];
      };
      register_standard_product_with_coupang_offer: {
        Args: {
          p_standard_product_id:string|null;
          p_standard_name:string;
          p_product_reference_url:string;
          p_listing_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          standard_product_id:string;
          catalog_product_id:string;
        }[];
      };
      register_standard_product_with_brand_and_coupang_offer: {
        Args: {
          p_standard_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          standard_product_id:string;
          catalog_product_id:string;
        }[];
      };
      register_standard_product_link_strict: {
        Args: {
          p_idempotency_key:string;
          p_case_id:string;
          p_input_fingerprint:string;
          p_target_fingerprint:string;
          p_standard_product_id:string|null;
          p_catalog_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_receipt_product_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          execution_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
        }[];
      };
      register_standard_product_link_strict_v2: {
        Args: {
          p_idempotency_key:string;
          p_case_id:string;
          p_input_fingerprint:string;
          p_target_fingerprint:string;
          p_receipt_id:string;
          p_receipt_item_id:string;
          p_receipt_observed_at:string;
          p_standard_product_id:string|null;
          p_catalog_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_receipt_product_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          execution_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
        }[];
      };
      register_standard_product_link_strict_v3: {
        Args: {
          p_idempotency_key:string;
          p_case_id:string;
          p_input_fingerprint:string;
          p_target_fingerprint:string;
          p_input_canonical_json:string;
          p_target_canonical_json:string;
          p_receipt_id:string;
          p_receipt_item_id:string;
          p_receipt_observed_at:string;
          p_standard_product_id:string|null;
          p_catalog_product_id:string|null;
          p_standard_name:string;
          p_brand_name:string|null;
          p_receipt_brand_name:string|null;
          p_official_brand_name:string|null;
          p_official_brand_source_label:string|null;
          p_product_reference_url:string;
          p_listing_name:string;
          p_receipt_product_name:string;
          p_specification_status:string;
          p_content_amount:number;
          p_content_unit:string;
          p_package_count:number;
          p_reference_unit:number;
          p_source_product_code:string;
          p_source_labels:string[];
          p_coupang_product_url:string;
          p_coupang_listed_price_krw:number;
          p_coupang_quantity:number;
          p_coupang_content_amount:number;
          p_coupang_content_unit:string;
          p_coupang_max_bundle_quantity:number|null;
          p_coupang_max_bundle_listed_price_krw:number|null;
        };
        Returns: {
          execution_id:string;
          standard_product_id:string;
          catalog_product_id:string;
          replayed:boolean;
        }[];
      };
      get_public_exact_standard_product_catalog_v2: {
        Args: Record<string, never>;
        Returns: {
          source_label:string;
          source_product_code:string;
          catalog_product_id:string;
          standard_product_id:string;
          standard_name:string;
          content_amount:number;
          content_unit:string;
          package_count:number;
          reference_unit:number;
          coupang_listed_price_krw:number|null;
          coupang_quantity:number|null;
          coupang_content_amount:number|null;
          coupang_content_unit:string|null;
          coupang_max_bundle_quantity:number|null;
          coupang_max_bundle_listed_price_krw:number|null;
          coupang_product_url:string|null;
          coupang_observed_at:string|null;
        }[];
      };
      get_public_exact_standard_product_catalog: {
        Args: Record<string, never>;
        Returns: {
          source_label:string;
          source_product_code:string;
          catalog_product_id:string;
          standard_product_id:string;
          standard_name:string;
          content_amount:number;
          content_unit:string;
          package_count:number;
          reference_unit:number;
          coupang_listed_price_krw:number|null;
          coupang_quantity:number|null;
          coupang_content_amount:number|null;
          coupang_content_unit:string|null;
          coupang_product_url:string|null;
          coupang_observed_at:string|null;
        }[];
      };
      get_public_standard_product_catalog: {
        Args: Record<string, never>;
        Returns: {
          source_product_code:string;
          catalog_product_id:string;
          standard_product_id:string;
          standard_name:string;
          content_amount:number;
          content_unit:string;
          package_count:number;
          reference_unit:number;
          coupang_listed_price_krw:number|null;
          coupang_quantity:number|null;
          coupang_content_amount:number|null;
          coupang_content_unit:string|null;
          coupang_product_url:string|null;
          coupang_observed_at:string|null;
        }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
