"use client";
import { useEffect, useMemo, useState } from "react";
import { JsonReceiptRepository } from "@/repositories/json-receipt.repository";
import { formatKrw, allocationQuantity, overview, recipientTotal, settlementMessage } from "@/domain/settlement";
import { persistSettlement, useSettlementStore } from "@/stores/settlement.store";
import styles from "./page.module.css";
const receipt=new JsonReceiptRepository().load();
type Sort="name"|"price"|"remaining";
export default function Home(){ const store=useSettlementStore(); const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [sort,setSort]=useState<Sort>("name");const [recipientName,setRecipientName]=useState("");const [message,setMessage]=useState(""); const [backupInput,setBackupInput]=useState("");
 // hydrate is intentionally called only once after the client store mounts.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>store.hydrate(receipt),[]); useEffect(()=>{if(store.hydrated) persistSettlement(receipt)},[store.recipients,store.allocations,store.settlementStatuses,store.hydrated]); const totals=overview(receipt,store); const items=useMemo(()=>receipt.items.filter(i=>`${i.productName} ${i.storeProductCode} ${i.purchaseNumbers.join(" ")}`.toLowerCase().includes(query.toLowerCase())).filter(i=>filter==="all"|| (filter==="complete"?allocationQuantity(i.id,store.allocations)===i.purchasedQuantity:allocationQuantity(i.id,store.allocations)===0)).sort((a,b)=>sort==="name"?a.productName.localeCompare(b.productName):sort==="price"?a.unitPriceKrw-b.unitPriceKrw:(a.purchasedQuantity-allocationQuantity(a.id,store.allocations))-(b.purchasedQuantity-allocationQuantity(b.id,store.allocations))),[query,filter,sort,store.allocations]);
 const action=(fn:()=>void)=>{try{fn();setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"처리 중 오류")}}; const download=()=>{const blob=new Blob([store.exportBackup(receipt.id)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="settlement-backup.json";link.click();URL.revokeObjectURL(link.href)};
 return <main className={styles.main}><header><p className={styles.eyebrow}>Milestone 1 · 로컬 전용</p><h1>물품 배분·정산</h1><p>{receipt.storeLabel} · {receipt.purchasedAt} · 영수증 관측가</p></header>{message&&<p role="alert" className={styles.error}>{message}</p>}
 <section className={styles.stats} aria-label="전체 현황"><Stat label="영수증 총액" value={formatKrw(receipt.totalPriceKrw)}/><Stat label="배분 금액" value={formatKrw(totals.allocatedKrw)}/><Stat label="미배분 금액" value={formatKrw(totals.unallocatedKrw)}/><Stat label="입금 완료" value={formatKrw(totals.paidKrw)}/><Stat label="수량" value={`${totals.allocatedQuantity} 배분 / ${totals.remainingQuantity} 잔여`}/></section>
 <section className={styles.section}><h2>수령자</h2><form className={styles.inline} onSubmit={e=>{e.preventDefault();action(()=>{store.addRecipient(recipientName);setRecipientName("")})}}><label htmlFor="recipient">이름</label><input id="recipient" value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="예: 민수"/><button type="submit">수령자 추가</button></form><div className={styles.recipients}>{store.recipients.map(r=><article key={r.id} className={styles.recipient}><strong>{r.name}</strong><span>{formatKrw(recipientTotal(receipt,r.id,store.allocations))}</span><button onClick={()=>{const name=prompt("새 이름",r.name);if(name)action(()=>store.renameRecipient(r.id,name))}}>이름 수정</button><button onClick={()=>{if(confirm(`${r.name}을 삭제할까요?`))action(()=>store.deleteRecipient(r.id))}}>삭제</button></article>)}</div></section>
 <section className={styles.section}><div className={styles.controls}><h2>물품 목록 <small>{items.length}/95</small></h2><label>검색<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="상품명 · 상품코드 · 구매번호"/></label><label>상태<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체</option><option value="unallocated">미배분</option><option value="complete">배분 완료</option></select></label><label>정렬<select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="name">이름</option><option value="price">가격</option><option value="remaining">잔여 수량</option></select></label></div><div className={styles.table}>{items.map(item=><Product key={item.id} item={item} recipients={store.recipients} allocations={store.allocations} onSave={(recipientId,quantity,memo)=>action(()=>store.saveAllocation(receipt,{receiptItemId:item.id,recipientId,quantity,memo}))}/>)}</div>{items.length===0&&<p>검색 결과가 없습니다.</p>}</section>
 <section className={styles.section}><h2>친구별 정산</h2>{store.recipients.length===0?<p>수령자를 추가하면 정산 내역이 표시됩니다.</p>:<div className={styles.settlements}>{store.recipients.map(r=>{const status=store.settlementStatuses.find(s=>s.recipientId===r.id);const rows=store.allocations.filter(a=>a.recipientId===r.id);return <article key={r.id} className={styles.settlement}><h3>{r.name} · {formatKrw(recipientTotal(receipt,r.id,store.allocations))}</h3>{rows.map(a=>{const i=receipt.items.find(x=>x.id===a.receiptItemId)!;return <p key={a.id}>{i.productName} {a.quantity}개 × {formatKrw(i.unitPriceKrw)} <button onClick={()=>store.deleteAllocation(a.id)}>배분 삭제</button></p>})}<label>전달<select value={status?.deliveryStatus} onChange={e=>store.setStatus(r.id,"deliveryStatus",e.target.value as never)}><option>준비 중</option><option>전달 완료</option></select></label><label>입금<select value={status?.paymentStatus} onChange={e=>store.setStatus(r.id,"paymentStatus",e.target.value as never)}><option>미입금</option><option>입금 완료</option></select></label><button onClick={()=>navigator.clipboard.writeText(settlementMessage(receipt,r,store.allocations)).then(()=>setMessage("정산 메시지를 복사했습니다."))}>카카오톡 정산 메시지 복사</button></article>})}</div>}</section>
 <section className={styles.section}><h2>백업 · 복원</h2><div className={styles.inline}><button onClick={download}>JSON 내보내기</button><label>JSON 붙여넣기<textarea value={backupInput} onChange={e=>setBackupInput(e.target.value)} /></label><button onClick={()=>action(()=>{store.importBackup(backupInput,receipt);setBackupInput("")})}>복원</button><button className={styles.danger} onClick={()=>{if(confirm("모든 정산 상태를 초기화할까요? 영수증 원본은 유지됩니다."))store.reset()}}>전체 초기화</button></div></section></main> }
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Product({item,recipients,allocations,onSave}:{item:typeof receipt.items[number];recipients:ReturnType<typeof useSettlementStore.getState>["recipients"];allocations:ReturnType<typeof useSettlementStore.getState>["allocations"];onSave:(recipientId:string,quantity:number,memo:string)=>void}){const [recipientId,setRecipientId]=useState("");const [quantity,setQuantity]=useState("1");const [memo,setMemo]=useState("");const allocated=allocationQuantity(item.id,allocations);const remaining=item.purchasedQuantity-allocated;return <article className={styles.product}><div><strong>{item.productName}</strong><small>코드 {item.storeProductCode} · 구매번호 {item.purchaseNumbers.join(", ")} · {item.confidence}</small></div><div><b>{formatKrw(item.unitPriceKrw)}</b><small>구매 {item.purchasedQuantity} · 배분 {allocated} · 잔여 {remaining}</small></div><div className={styles.allocate}><select aria-label={`${item.productName} 수령자`} value={recipientId} onChange={e=>setRecipientId(e.target.value)}><option value="">수령자 선택</option>{recipients.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input aria-label={`${item.productName} 수량`} type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/><input aria-label={`${item.productName} 메모`} value={memo} onChange={e=>setMemo(e.target.value)} placeholder="메모 (선택)"/><button disabled={!recipientId||remaining===0} onClick={()=>onSave(recipientId,Number(quantity),memo)}>담기</button></div></article>}
