// Generated by scripts/sync-public-receipts.ts. Do not edit manually.
import receipt_2026_05_08_001 from "../../data/public/receipts/2026-05-08_001.json";
import receipt_2026_06_07_001 from "../../data/public/receipts/2026-06-07_001.json";
import receipt_2026_06_12_001 from "../../data/public/receipts/2026-06-12_001.json";
import receipt_2026_07_14_001 from "../../data/public/receipts/2026-07-14_001.json";

export const publicReceiptFiles = {
  "2026-05-08_001": receipt_2026_05_08_001,
  "2026-06-07_001": receipt_2026_06_07_001,
  "2026-06-12_001": receipt_2026_06_12_001,
  "2026-07-14_001": receipt_2026_07_14_001,
} as const;
