import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  assertPublicReceiptObservationLinks,
  buildPublicObservationBundle,
  PublicObservationBundleSchema,
} from "../src/domain/public-observation";
import {
  assertNoForbiddenPublicReceiptKeys,
  assertNoForbiddenSourceValues,
  assertPublicReceiptCollection,
  buildPublicReceiptFiles,
  buildPublicReceiptIndex,
  PublicReceiptIndexSchema,
  publicReceiptFilesToReceipts,
} from "../src/domain/public-receipt";
import { loadPrivateReceiptPublicationSources } from "./private-receipt-source";
import rawMerchantCatalogProfiles from "../data/curation/receipt-merchant-catalog-profiles.v1.json";
import { applyReceiptMerchantCatalogProfiles } from "../src/domain/receipt-merchant-catalog-profile";

const publicDirectory = path.join(process.cwd(), "data", "public");
const receiptDirectory = path.join(publicDirectory, "receipts");
const receiptIndexPath = path.join(receiptDirectory, "index.v1.json");
const observationOutputPath = path.join(publicDirectory, "product-observations.v3.json");
const registryOutputPath = path.join(process.cwd(), "src", "repositories", "public-receipt-files.generated.ts");
const checkOnly = process.argv.includes("--check");

async function readRequiredJson(filePath: string) {
  try {
    return JSON.parse(await readFile(filePath, "utf8")) as unknown;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") throw new Error(`공개 데이터 파일이 없습니다: ${path.relative(process.cwd(), filePath)}`);
    throw error;
  }
}

async function loadPublicReceiptFiles() {
  const index = PublicReceiptIndexSchema.parse(await readRequiredJson(receiptIndexPath));
  const receipts = await Promise.all(index.receipts.map((entry) => readRequiredJson(path.join(receiptDirectory, entry.fileName))));
  return { index, receipts };
}

function validatePublicData(receiptIndexInput: unknown, receiptInputs: unknown[], observationInput: unknown) {
  const collection = assertPublicReceiptCollection(receiptIndexInput, receiptInputs);
  const observationBundle = PublicObservationBundleSchema.parse(observationInput);
  assertNoForbiddenPublicReceiptKeys(collection.receipts);
  assertNoForbiddenSourceValues(collection.receipts, []);
  assertPublicReceiptObservationLinks(collection.index, collection.receipts, observationBundle);
  return { ...collection, observationBundle };
}

function buildRegistry(receipts: Array<{ id: string; fileName: string }>) {
  const imports = receipts.map((receipt) => {
    const symbol = `receipt_${receipt.id.replace(/[^A-Za-z0-9]/g, "_")}`;
    return { ...receipt, symbol };
  });
  return [
    "// Generated by scripts/sync-public-receipts.ts. Do not edit manually.",
    ...imports.map((receipt) => `import ${receipt.symbol} from "../../data/public/receipts/${receipt.fileName}";`),
    "",
    "export const publicReceiptFiles = {",
    ...imports.map((receipt) => `  \"${receipt.id}\": ${receipt.symbol},`),
    "} as const;",
    "",
  ].join("\n");
}

async function removeStaleReceiptFiles(expectedFileNames: Set<string>) {
  const existing = await readdir(receiptDirectory);
  await Promise.all(existing
    .filter((fileName) => /^\d{4}-\d{2}-\d{2}_\d{3}\.json$/.test(fileName) && !expectedFileNames.has(fileName))
    .map((fileName) => unlink(path.join(receiptDirectory, fileName))));
}

async function checkPublicReceipts() {
  const files = await loadPublicReceiptFiles();
  const result = validatePublicData(files.index, files.receipts, await readRequiredJson(observationOutputPath));
  console.log(`공개 영수증 검증 통과 · 영수증 ${result.receipts.length}건 · 관측 ${result.observationBundle.observations.length}건 · index revision ${result.index.revision}`);
}

async function syncPublicReceipts() {
  const source = await loadPrivateReceiptPublicationSources();
  if (source.warnings.length > 0) throw new Error(`private 영수증 경고 ${source.warnings.length}건이 있어 공개 파일 생성을 중단했습니다.`);
  if (source.sources.length === 0) throw new Error("공개 영수증으로 변환할 private 영수증이 없습니다.");

  const profiled = applyReceiptMerchantCatalogProfiles(
    source.sources,
    rawMerchantCatalogProfiles,
  );
  const receiptFiles = buildPublicReceiptFiles(profiled.sources);
  const receiptIndex = buildPublicReceiptIndex(receiptFiles);
  const receipts = publicReceiptFilesToReceipts(receiptFiles);
  const observationBundle = buildPublicObservationBundle(receipts, receiptIndex.revision);
  assertNoForbiddenSourceValues(receiptFiles, source.sources);
  validatePublicData(receiptIndex, receiptFiles, observationBundle);

  await mkdir(receiptDirectory, { recursive: true });
  await Promise.all([
    writeFile(receiptIndexPath, `${JSON.stringify(receiptIndex, null, 2)}\n`, "utf8"),
    writeFile(observationOutputPath, `${JSON.stringify(observationBundle, null, 2)}\n`, "utf8"),
    writeFile(registryOutputPath, buildRegistry(receiptFiles), "utf8"),
    ...receiptFiles.map((receipt) => writeFile(path.join(receiptDirectory, receipt.fileName), `${JSON.stringify(receipt, null, 2)}\n`, "utf8")),
  ]);
  await removeStaleReceiptFiles(new Set(receiptFiles.map((receipt) => receipt.fileName)));
  console.log(`공개 영수증 갱신 완료 · 개별 JSON ${receiptFiles.length}건 · 관측 ${observationBundle.observations.length}건 · 판매처 프로필 적용 ${profiled.applied.length}건 · index revision ${receiptIndex.revision}`);
}

(checkOnly ? checkPublicReceipts() : syncPublicReceipts()).catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
